export { default as AdaptiveIcon } from './adaptive-icon.png';
export { default as BellIcon } from './BellIcon.png';
export { default as Favicon } from './favicon.png';
export { default as FormIllustrationPng } from './FormIllustration.png';
export { default as FormIllustrationSvg } from './FormIllustration.svg';
export { default as GeekyantsLogoPng } from './Geekyants_Logo.png';
export { default as GeekyantsLogoSvg } from './Geekyants_Logo.svg';
export { default as GoogleIcon } from './Google_Icon.svg';
export { default as Icon } from './icon.png';
export { default as LoginIllustrationPng } from './Login_Illustration.png';
export { default as LoginIllustrationSvg } from './Login_Illustration.svg';
export { default as MenuIconPng } from './MenuIcon.png';
export { default as MenuIconSvg } from './MenuIcon.svg';
export { default as SearchIcon } from './SearchIcon.png';
export { default as Splash } from './splash.png';
export { default as HrmsLogo } from './HrmsLogo.png';
export { default as MarkAttendance } from './MarkAttendance.svg';
export {default as LeaveRequest} from './leaveRequest.svg';
export {default as Projects} from './projects.svg';
export {default as AttendanceRecords} from './AttendanceRecords.svg';
export {default as TimesheetRecords} from './TimesheetRecords.svg';
export {default as LogTimesheet} from './LogTimesheet.svg';
export {default as LeavesRecord} from './LeavesRecord.svg';
export {default as Payroll} from './Payroll.svg';